# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rD5W51fhiVyFsJqabBLRlOaYfqwD8E5I
"""

import pandas as pd

xls = pd.ExcelFile("dados e-commerce.xlsx", engine="openpyxl")

df_produtos = xls.parse("dados_produtos")

print(df_produtos.columns.tolist())

df_produtos.isnull().sum()

df_produtos['categoria_produto'] = df_produtos['categoria_produto'].ffill()
df_produtos['tamanho_nome_produto'] = df_produtos['tamanho_nome_produto'].ffill()
df_produtos['tamanho_descricao_produto'] = df_produtos['tamanho_descricao_produto'].ffill()
df_produtos['peso_produto_g'] = df_produtos['peso_produto_g'].ffill()
df_produtos['comprimento_produto_cm'] = df_produtos['comprimento_produto_cm'].ffill()
df_produtos['altura_produto_cm'] = df_produtos['altura_produto_cm'].ffill()
df_produtos['largura_produto_cm'] = df_produtos['largura_produto_cm'].ffill()

df_produtos.to_csv("dados_ecommerce_limpo.csv", index=False, encoding="utf-8-sig")

from google.colab import files

files.download("dados_ecommerce_limpo.csv")