# -*- coding: utf-8 -*-
"""limpeza_dados_ecommerce.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EuyCRrBt1sO2aPXE8h5QXr10Px0aWQLC
"""

import pandas as pd

df = pd.read_excel('dados_ecommerce.xlsx')

display(df)

df.isnull().sum()

df.drop_duplicates(inplace=True)

df['Avaliacao'] = df['Avaliacao'].fillna(df['Avaliacao'].median())